### ISSUE TITLE
pulseaudio -k cannot be executed

### ISSUE THREAD

**Issue by koarlmichael** [lagerimsi-ds/debian-buster_bluetooth_aptX-LDAC#12]
The script only works if I enter the command "systemctl --user unmask pulseaudio.socket" an "systemctl --user start pulseaudio.service".
Otherwise, pulseaudio -k cannot be executed. This is necessary after each restart. 

Is there an easy way to get everything back into the state. I'm using Debian testing here.

**Comment by lagerimsi-ds** [comment]
Well, as far as I know, even in bookworm pulseaudio is still the standard audio system.  This way it should be startet automatically with every fresh installation.
So I don't know why you had to unmask (make it able to start) pulseaudio (btw. the unit/service, not the socket!). Masked it in front?

After unmasking you should also "enable" the pulseaudio service to start after every reboot.

To get rid of the packet you installed via this scipt use "dpkg -r <packet name>".

**Comment by lagerimsi-ds** [comment]
installed packages are "libldac" and "pulseaudio-module-bluetooth"

might be you have to reinstall "pulseaudio-module-bluetooth" from the original repositories not to loose pulseaudio-bluetooth-support.
