### ISSUE TITLE
Problem for Debian 11

### ISSUE THREAD

**Issue by clasicus** [lagerimsi-ds/debian-buster_bluetooth_aptX-LDAC#13]
Hello, I use Debian 11, but when I try to install by shell file, every time I have next:

bluetooth-aptx-ldac.sh: 21: [[: not found
bluetooth-aptx-ldac.sh: 39: [[: not found
bluetooth-aptx-ldac.sh: 43: [[: not found
-E This is no Debian Buster or Bullseye or Bookwork (testing). Goodbye!

Could you say, please, what can be a problem? 
Thank you!

**Comment by lagerimsi-ds** [comment]
lsb-release package is now prequisite - typo fixed
(... the command *lsb_release' is used to gather debian version infos...)
