### ISSUE TITLE
fdkaac -> libfdk-aac2

### ISSUE THREAD

**Issue by brknkfr** [lagerimsi-ds/debian-buster_bluetooth_aptX-LDAC#14]
I set an a raspberry arm64 bullseye and used your script to install the codecs. Unfortunately the package `fdkaac` is not available in raspbians bullseye (probably booksworm too), it's called `libfdk-aac2`

**Comment by lagerimsi-ds** [comment]
as you can see here: 
https://packages.debian.org/search?searchon=names&keywords=fdkaac
this is NOT the case.

also libfdk-aac2 is installed as an dependency on libfdk-aac-dev

try: apt show libfdk-aac-dev

have a nice day :-)

**Comment by brknkfr** [comment]
I'm sorry, you're wrong. Please read carefully, I'm on `arm64` and the package is not there: https://packages.debian.org/search?suite=default&arch=arm64&searchon=names&keywords=fdkaac

Btw, the package `fdkaac` only is like a "transitional" name for actually installing `libfdk-aac2`.

Thank you for fixing and have a nice day!

**Comment by lagerimsi-ds** [comment]
You are right in the case the package doesn't exist for arm architectures.
On the other side do you know if things break leaving the ```fdkaac``` out of the installing process?

In this case and maintaining/extending things it would be very helpful if you want things fixed to provide a bit more infos here.
Maybe also a solution.
Best an already tested one.

It always takes a quite lot of time to get all infos together if some new usecase appears.

May you be so kind to set up several virtual machines with the different versions of Debian and architectures then test things work out if the package is fdkaac is not installed? If you have real hardware, this don't have to be VMs anyway.

Please provide me also with the output of your tests then. To proove things work out.

**Comment by lagerimsi-ds** [comment]
easiest way (depending how mouch you want to help here and how urgent your request is for you) might be to ask the debian maintainers to provide this package also for the arm architecture.

I will mark this project not supporting ARM for now.
Your help is very welcome :-)

**Comment by brknkfr** [comment]
Check https://github.com/lagerimsi-ds/debian-buster_bluetooth_aptX-LDAC/pull/15

**Comment by lagerimsi-ds** [comment]
shouldn't be be closed until now - solved but waiting for approval as I don't own an ARM-board to test.
amd64 architecture is not affected by changes and future proof as well as easy to maintain if other differences between architectures occur.
details on changes see https://github.com/lagerimsi-ds/debian-buster_bluetooth_aptX-LDAC/pull/15
so I reopen and close again when approved.

**Comment by lagerimsi-ds** [comment]
main commit of changes (some fixes came by afterwards!):
https://github.com/lagerimsi-ds/debian-buster_bluetooth_aptX-LDAC/commit/ec64082e3ad2b2c6fbc7a768ef265c1cd120b577
