### ISSUE TITLE
Media Codec - SBC not aptX

### ISSUE THREAD

**Issue by koarlmichael** [lagerimsi-ds/debian-buster_bluetooth_aptX-LDAC#3]
On _Debian Bullseye - testing_ the Script works fine.

But the aptx codec is not loaded, tried to reconnect the speakers several times.

**sudo hcidump | grep -A 10 -B 10 'Set config' output:**

count 32
          record #0
              aid 0x0009 (BTProfileDescList)
                 < < uuid-16 0x110d (AdvAudio) uint 0x103 > >
          record #1
              aid 0x0009 (BTProfileDescList)
                 < < uuid-16 0x110d (AdvAudio) uint 0x103 > >
          cont 00
< ACL data: handle 256 flags 0x00 dlen 18
    L2CAP(d): cid 0x0141 len 14 [psm 25]
      AVDTP(s): Set config cmd: transaction 9 nsp 0x00
        ACP SEID 1 - INT SEID 3
        Media Transport
        Media Codec - SBC
          44.1kHz 
          JointStereo 
          16 Blocks
          8 Subbands
          Loudness 
          Bitpool Range 2-53
> HCI Event: Number of Completed Packets (0x13) plen 5
--
> HCI Event: Number of Completed Packets (0x13) plen 5
    handle 256 packets 1
> ACL data: handle 256 flags 0x02 dlen 12
    L2CAP(s): Disconn req: dcid 0x0042 scid 0x0182
< ACL data: handle 256 flags 0x00 dlen 12
    L2CAP(s): Disconn rsp: dcid 0x0042 scid 0x0182
> HCI Event: Number of Completed Packets (0x13) plen 5
    handle 256 packets 1
> ACL data: handle 256 flags 0x02 dlen 6
    L2CAP(d): cid 0x0041 len 2 [psm 25]
      AVDTP(s): Set config rsp: transaction 9 nsp 0x00
< ACL data: handle 256 flags 0x00 dlen 7
    L2CAP(d): cid 0x0141 len 3 [psm 25]
      AVDTP(s): Open cmd: transaction 10 nsp 0x00
        ACP SEID 1
> HCI Event: Number of Completed Packets (0x13) plen 5
    handle 256 packets 1
> ACL data: handle 256 flags 0x02 dlen 6
    L2CAP(d): cid 0x0041 len 2 [psm 25]
      AVDTP(s): Open rsp: transaction 10 nsp 0x00
< ACL data: handle 256 flags 0x00 dlen 12

**Comment by lagerimsi-ds** [comment]
aptX is proprietary - you might need a bluetooth dongle that is capable of aptX.

as you can read here - android 10+ gets the license for free now ... might happen it is available soon to others, too.
https://en.wikipedia.org/wiki/AptX

**Comment by lagerimsi-ds** [comment]
libavcodec is needed for aptX.will change it soon...

**Comment by lagerimsi-ds** [comment]
I tried now several times - forcing LDAC-HQ or not, fullfilling all requirements - no difference here with my JBL loudspeaker.
With headphones (supporting LDAC and aptX HD - not fullfilling the requirements for compiling LDAC so just aptX availabe) the headphones connected quite well by aptX HD - even not named like that in the output of hcidump (was called non-A2DP there). 
This is just a guess, but I remember JBL sending a firmware update to connect more than one loudspeaker not compatible with older loudspeakers - also not of their own brand. This might be off the standard and thereby aptX not usable?

proof me wrong - I would be glad!

Know a workaround? even better!


--> this might not be the case with your loudspeaker/headphones! :-)

**Comment by lagerimsi-ds** [comment]
as aptX is working - I close this issue...

**Comment by lagerimsi-ds** [comment]
as aptX is working - I close this issue...

**Comment by koarlmichael** [comment]
> I tried now several times - forcing LDAC-HQ or not, fullfilling all requirements - no difference here with my JBL loudspeaker.
> With headphones (supporting LDAC and aptX HD - not fullfilling the requirements for compiling LDAC so just aptX availabe) the headphones connected quite well by aptX HD - even not named like that in the output of hcidump (was called non-A2DP there).
> This is just a guess, but I remember JBL sending a firmware update to connect more than one loudspeaker not compatible with older loudspeakers - also not of their own brand. This might be off the standard and thereby aptX not usable?
> 
> proof me wrong - I would be glad!
> 
> Know a workaround? even better!
> 
> --> this might not be the case with your loudspeaker/headphones! :-)

Thank you, now it works:

Media Codec - non-A2DP (aptX)
          44.1kHz 
          Stereo
