### ISSUE TITLE
Enable donations

### ISSUE THREAD

**Issue by cflewis** [lagerimsi-ds/debian-buster_bluetooth_aptX-LDAC#4]
Hi there,
This script was really awesome and got everything working in one click for Debian. After months of hassle, this made my day. I want to donate a coffee to you somehow, so please add something to this issue or on your README :)

**Comment by lagerimsi-ds** [comment]
wrote it because I had the need for it.
if it helped you also I am glad to be able to help you and make your life easier.
enjoy!
