### ISSUE TITLE
Failed to change profile to a2dp_sink_aptx_hd

### ISSUE THREAD

**Issue by gerroon** [lagerimsi-ds/debian-buster_bluetooth_aptX-LDAC#5]
Hi

I installed your script, everything went fine but it seems like I can only use aptx but not aptx-hd. Actually none of those new profiles except the aptx is available.Is this a limitation because I compiled it on Debian testing?

thanks

**Comment by lagerimsi-ds** [comment]
May you provide me with the logs and output while installing/compiling the codecs?
Quite difficult to say without these information provided ;-)
Best just install again and paste the output here or provide a link to the pastebin service of your choice.

**Comment by lagerimsi-ds** [comment]
should be fixed with adding the depending dev-package for install
