### ISSUE TITLE
AAC support not compiled

### ISSUE THREAD

**Issue by Tuxicoman2** [lagerimsi-ds/debian-buster_bluetooth_aptX-LDAC#6]
Hi,
Thanks for your script.

I found it misses to install the "libfdk-aac-dev" package.
This would add the support for AAC during the compilation which is the only "improved BT audio codec" supported by Bose headphones for IE.

**Comment by lagerimsi-ds** [comment]
added to "apt install" line...

give it a try :-)

may you tell me if you find yourself with an enabled aptx connection?

**Comment by lagerimsi-ds** [comment]
broke installation because this package doesn't exist in debian - did you make more comments like this in other projects?

removed  changes made upon this troll
