### ISSUE TITLE
EH5 pulseaudio-modules-bt archived

### ISSUE THREAD

**Issue by AJJLagerweij** [lagerimsi-ds/debian-buster_bluetooth_aptX-LDAC#7]
I want to thank you for your script, it helped me greatly. I just wanted to inform you that EH5 stopped developing his `pulseaudio` module, see EHfive/pulseaudio-modules-bt#154. This doesn't break everything immediately but might cause problems in the future.

From what I see this had 2 reasons:
1. EH5 moved from `pulsaudio` to `pipewire`.
2. Vanilla `pulsoaudio` has [merged support for Bluetooth devices and codec switching](https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/440).

I haven't tested this, and it might not resolve all Bluetooth audio problems, but might require a change in your installer.

**Comment by berglh** [comment]
Just FYI for the Ubuntu peeps out there; the version of `pulseaudio` shipped with Ubuntu 21.04 did not include the latest GStreamer codec support for `pulseaudio` even though it's been merged into master.  I went ahead and produced debs from the EH5 repo that work with 21.04 on my PPA [berglh/pulseaudio-a2dp](https://launchpad.net/~berglh/+archive/ubuntu/pulseaudio-a2dp/+packages). I believe the version of `pulseaudio` support is `14.2` from memory.

Additionally, `pipewire` is not currently default in Ubuntu 21.04, although I hear that it does work with a bit of finagling.  We will anticipate that Gnome Shell will push forward and Ubuntu will be forced to move to `pipewire` by default at some point in the future.

I additionally assume at some point `pulseaudio` will be updated in Ubuntu 21.04 to include GStreamer support.  In that case you should remove the packages provided in my PPA, delete the PPA from your apt sources and install the regular `pulseaudio bluetooth modules` package.

**Comment by lagerimsi-ds** [comment]
for now no need - sid is not supported by this script just stable releases of debian

**Comment by lagerimsi-ds** [comment]
no need for now - just stable debian releases supported
