### ISSUE TITLE
Compilation failed because of missing ltdl.h

### ISSUE THREAD

**Issue by rizaumami** [lagerimsi-ds/debian-buster_bluetooth_aptX-LDAC#9]
Compilation failed on Debian Sid because of missing `ltdl.h`.

```
/tmp/tmp.zT9H62RHRy/pulseaudio-modules-bt/pa/src/pulsecore/module.h:24:10: fatal error: ltdl.h: No such file or directory
```

Solution: install `libltdl-dev` package.

Perhaps this package should be included as dependency in the script.

Also, I need to issue `pulseaudio --start` to restart pulseaudio after it has been killed.

**Comment by lagerimsi-ds** [comment]
just stable debian versions supported - sid is unstable

**Comment by lagerimsi-ds** [comment]
why don't you use the already available distinction of debian versions and make a merge request foryour changes so we can improve this script to support more than just the stable version?
